// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5F4MZlOJ7ubcJ46p2dsjZgs83WvIPcG8',
    appId: '1:82807974550:android:3d29339551f8c4dd8d70b7',
    messagingSenderId: '82807974550',
    projectId: 'tps-app-dd7b0',
    storageBucket: 'tps-app-dd7b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfl0vysdzWBxpgPDDKckCGrT8Y-qLpcsg',
    appId: '1:82807974550:ios:8e5e3f97cea1ec9e8d70b7',
    messagingSenderId: '82807974550',
    projectId: 'tps-app-dd7b0',
    storageBucket: 'tps-app-dd7b0.firebasestorage.app',
    iosBundleId: 'com.example.tps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmjF8h5JbZwX4Lsm27stoQPxBfiqMQ8z8',
    appId: '1:82807974550:web:2c88c052c97f6e4f8d70b7',
    messagingSenderId: '82807974550',
    projectId: 'tps-app-dd7b0',
    authDomain: 'tps-app-dd7b0.firebaseapp.com',
    storageBucket: 'tps-app-dd7b0.firebasestorage.app',
    measurementId: 'G-1M5BCJGVR5',
  );
}
